# Capture configuration
# cameras: List of camera IDs or names (integers for Linux, strings for Windows/macOS)
# output_dir: Directory to save frames
# fps: Frames per second
# duration: Optional capture duration in seconds; omit or set null for continuous
cameras: [0]
output_dir: ./frames
fps: 30
duration: null
